### ISSUE TITLE
Hashcat_ wordlist bug

### ISSUE THREAD

**Issue by Sinapssis** [fpolit/ama-framework#2]
https://github.com/fpolit/ama-framework/blob/1f07f3241d3a3db5935da7662b1297a6d1888a17/ama/core/modules/attack/hashes/hashcat_wordlist.py#L178

**Comment by glozanoa** [comment]
Hello @Sinapssis , that bug was a typo. I have update the attack modules (related to john and hashcat), so you can use them now.
